### ISSUE TITLE
not_in_creative_inventory group for tinted glass

### ISSUE THREAD

**Issue by thomasrudin** [6r1d/minetest_new_glass#1]
The following node are showing up in the crafting guide:

* `new_glass:super_steel_framed_obsidian_glass_tinted`
* `new_glass:ultra_steel_framed_obsidian_glass_tinted` 
* `new_glass:smoked_glass_tinted`

This isn't that bad but they aren't directly craftable and the `framedglass` mod hides those too with the group attribute `not_in_creative_inventory = 1`

See: https://github.com/minetest-mods/framedglass/blob/b7e9614ab417d6b34144e92103bddd664583a483/init.lua#L98

**Comment by 6r1d** [comment]
Well, I hope 8dafc30db88f2edeb9a52c1a1e6db253416a6eba fixes that. I am not sure: game was just showing both types, now it doesn't.

**Comment by thomasrudin** [comment]
cool, i'll close this then...
