### ISSUE TITLE
Different frame texures for obsidian_glow_* glass

### ISSUE THREAD

**Issue by thomasrudin** [6r1d/minetest_new_glass#2]
Just a minor nitpick :smile: 
It would look good if the frames of the `obsidian_glow_*` glass types would have a different frame-texture, just to make it easier to distinguish them from the *normal* nodes..

**Comment by 6r1d** [comment]
Done in b1c2fd4116a8c4634cb738ddfe51d988f97e05a3.
I agree with the idea, though I'd like for all framed glasses to connect in the end. Tinted obsidian glass connects horizontally sometimes, for example, and it's useful for art. :-)
