### ISSUE TITLE
Radiation resistance

### ISSUE THREAD

**Issue by zbx-pandorabox** [6r1d/minetest_new_glass#5]
Hi, nice mod! What do you think about "radiation resistance"(defined in technic mod) for new glass nodes?

**Comment by 6r1d** [comment]
Hello and thanks! Like [there](https://github.com/minetest-mods/technic/blob/master/technic/radiation.lua)? Is that a group value?

How about `25` for framed glowing glass and `23` for a dark glass?

Let's discuss!
@thomasrudin-mt @SwissalpS @S-S-X @OgelGames

**Comment by SwissalpS** [comment]
I don't quite see the point. IRL X-ray-glass contains lead and needs to be at least 12 times thicker than lead. So to get the equivalence of one node of Pb you would need so much space that you are anyway protected by distance.
Probably I don't have enough grasp on the subject.

**Comment by SwissalpS** [comment]
Disregarding IRL and only looking at that list, I think 25 is still rather high.

**Comment by OgelGames** [comment]
I agree with @SwissalpS, if it's going to be realistic at all, then it will basically be pointless.

On the other hand, if realism was discarded, and the glass was going to be radiation resistant, I'd say to make it a separate specialized (expensive) glass node.

**Comment by zbx-pandorabox** [comment]
25 or 26 sounds too high in my opinion. In radiation.lua have obsidian glass 18, why don't use the same value?
New lead doped framed obsidian glass, class(mod) "rad_res_glass" with better rad protection can be interresting.
